<?php

namespace LIV\AppBundle\Repository;

/**
 * EventCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEventByCategorySlug($slug)
    {
        $queryBuilder = $this->createqueryBuilder('ec')
            ->where('ec.slug = :slug')
            ->setParameter('slug', $slug)
            ->leftJoin('ec.events', 'evts')
            ->addSelect('evts')
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
