<?php

namespace LIV\AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneFullBySlug($slug)
    {
        $queryBuilder = $this->createQueryBuilder('evt')
            ->where("evt.slug = :slug")
            ->setParameter('slug', $slug)
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
