<?php

namespace LIV\AppBundle\Repository;

/**
 * InterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithImages()
    {
        $queryBuilder = $this->createQueryBuilder('intw')
            ->where("intw.id >= 0")
            ->leftJoin('intw.images', 'imgs')
            ->addSelect('imgs')
        ;

        return $queryBuilder->getQuery()->getArrayResult();
    }

    public function findOneBySlugWithImages($slug)
    {
        $queryBuilder = $this->createQueryBuilder('intw')
            ->where("intw.slug = :slug")
            ->setParameter('slug', $slug)
            ->leftJoin('intw.images', 'imgs')
            ->addSelect('imgs')
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
