<?php

namespace LIV\AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneFullBySlug($slug)
    {
        $queryBuilder = $this->createQueryBuilder('plcs')
            ->where("plcs.slug = :slug")
            ->setParameter('slug', $slug)
            ->leftJoin('plcs.address', 'ddrss')
            ->addSelect('ddrss')
            ->leftJoin('plcs.images', 'mgs')
            ->addSelect('mgs')
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
