<?php

namespace LIV\AppBundle\Repository;

/**
 * placeImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceImageRepository extends \Doctrine\ORM\EntityRepository
{
}
