<?php

namespace LIV\AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneFullByTag($tagName)
    {
        $queryBuilder = $this->createQueryBuilder('tag')
            ->where("tag.name = :name")
            ->setParameter('name', $tagName)
            ->leftJoin('tag.places', 'plcs')
            ->addSelect('plcs')
            ->leftJoin('plcs.images', 'mgs')
            ->addSelect('mgs')
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
